spring.application.name=cloudforge

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cloudforge}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:cloudforgeSecretKeyForJwtAuthentication2026CloudForgeProjectSecureKey123}
jwt.expiration=${JWT_EXPIRATION:86400000}